In [180]:
# Tratar números infinitos e NaN. Melhor colocá-los como 0.

# Alterar os dados do dataset. Ao invés dos valores brutos, colocar a variação das contas por empresa ao longo dos semestres.

<a href='https://www.idinheiro.com.br/cnpj-empresas-listadas-b3/'> CNPJ e Ticker </a>

<h1 style='font-size:40px'> Stock Price Variation Predictor</h1>
<div> 
    <ul style='font-size:20px'> 
        <li> 
            The present project aims to create a stock price variation predictor using the  BOVESPA corporations' fundamentals. 
        </li>
        <li> 
            The model must estimate the given quarter's 80th percentile variation using the financial statements from the previous quarter.
        </li>
    </ul>
</div>

<h2 style='font-size:30px'> Building the dataset</h2>
<div> 
    <ul style='font-size:20px'> 
        <li> 
            Unlike most of the ML projects out there, in this one we'll face the challenge of making the dataset with which our models will carry out their predictions.
        </li>
        <li> 
            We are going to use wget in order to download the files and extract the financial statements.
        </li>
    </ul>
</div>

<a href='https://www.youtube.com/watch?v=LCMgVO1BOVQ&t=659s'> Link Tutorial</a>

In [2]:
import wget
import pandas as pd
from datetime import date
from zipfile import ZipFile
from pathlib import Path
import os
import numpy as np

In [9]:
import wget
import pandas as pd
from datetime import date
from zipfile import ZipFile
from pathlib import Path
import os

# The data source to the financial statements is going to be the URL below.
data_source = 'http://dados.cvm.gov.br/dados/CIA_ABERTA/DOC/ITR/DADOS/'

# Listing the documents from 2015 until last year.
current_year = date.today().year
zip_files = [f'itr_cia_aberta_{year}.zip' for year in range(2015, current_year)]

# Downloading the files and extracting their contents.
for file in zip_files:
    wget.download(data_source + file)
    with ZipFile(file, 'r') as zip_file:
        zip_file.extractall('Statements')
    # After the extraction is completed, we are able to delete the zip file.
    os.remove(file)

# The zip files contained two kinds of reports, the ones with '_con_' and others with '_ind_' in their names.
# Since we are going to use only the first sort of document, we'll remove the '_ind_' ones.

# Also, there were two kinds of DMPL statements, the '_MD_' and the '_MI_'. I ch
for file in Path('Statements').iterdir():
    if '_ind_' in file.name or '_MI_' in file.name:
        os.remove(file)

100% [....................................................] 29984400 / 29984400

In [20]:
with open('.gitignore', 'w') as git:
    for file in os.listdir('Statements'):
        git.write(f'Statements/{file}\n')
        
git.close()

In [38]:
from re import search
# This function creates a DataFrame with all the reports of a given kind of statement.
def unite_reports(type_statement):
    df = pd.DataFrame()
    #financial_statements = '(BPA|BPP|DFC|DMPL|DRA|DRE|DVA)'#['BPA', 'BPP', 'DFC', 'DMPL', 'DRA', 'DRE', 'DVA']
    for file in os.listdir('Statements'):
        if search(type_statement, file):
            #print(1)
            financial_statement_df = pd.read_csv(f'Statements/{file}', encoding='ISO-8859-1', sep=';', parse_dates=['DT_FIM_EXERC'])
            financial_statement_df = financial_statement_df.query('''ORDEM_EXERC=='ÚLTIMO' & ST_CONTA_FIXA=='S' & VERSAO==1 ''')
            df = pd.concat([df, financial_statement_df])
    pivot = pd.pivot_table(df, values='VL_CONTA', columns='CD_CONTA', index=['CNPJ_CIA', 'DT_FIM_EXERC'])
    # Retrieving a DataFrame with the accounts percentage change. Removing the lines that based the pct change comparison.
    return pivot.groupby('CNPJ_CIA').pct_change().dropna(how='all').fillna(method='bfill')

# This method converts the DF's level 1 data type to PeriodIndex.
def period_index(df):
    quarter_index = pd.PeriodIndex(df.xs(key=slice(None), level=0).index, freq='Q')
    return df.set_index([df.xs(key=slice(None), level=1).index , quarter_index])

# The 'dataset' function creates the final dataset by appending the results of 'unite_reports' for every statement kind available.
def dataset():
    df = unite_reports('BPA')
    for report in ['BPP', 'DFC', 'DMPL', 'DRA', 'DRE', 'DVA']:
        df = df.join(unite_reports(report))
    # Here, we are filtering out corporations with less than 12 quarters of available data.    
    sizes = df.groupby('CNPJ_CIA').size()
    df.loc(axis=0)[sizes[sizes>12].index,:]
    return period_index(df)

In [39]:
df = dataset()

In [45]:
df.loc(axis=0)['97.837.181/0001-47']

CD_CONTA,1,1.01,1.01.01,1.01.02,1.01.02.01,1.01.02.01.01,1.01.02.01.02,1.01.02.02,1.01.02.02.01,1.01.02.03,...,7.11.03,7.11.03.01,7.11.03.02,7.11.03.03,7.11.04,7.11.04.01,7.11.04.02,7.11.04.03,7.11.04.04,7.11.05
DT_FIM_EXERC,,,,,,,,,,,,,,,,,,,,,
2015Q2,-0.009891,-0.019241,-0.043316,inf,NaN,NaN,NaN,inf,inf,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015Q3,0.042077,0.045841,-0.001585,inf,NaN,NaN,NaN,inf,inf,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016Q1,-0.050565,-0.109130,-0.222650,inf,NaN,NaN,NaN,inf,inf,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016Q2,0.069367,0.247647,0.835595,inf,NaN,NaN,NaN,inf,inf,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016Q3,-0.013579,-0.045100,-0.086860,inf,NaN,NaN,NaN,inf,inf,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017Q1,-0.011270,-0.011680,-0.026748,inf,NaN,NaN,NaN,inf,inf,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017Q3,-0.011991,-0.034886,-0.247049,inf,NaN,NaN,NaN,inf,inf,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018Q1,0.018115,-0.018968,-0.127882,-1.0,NaN,NaN,NaN,-1.0,-1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018Q2,0.031721,0.156106,0.032131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018Q3,0.051197,0.164436,0.260204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019Q1,-0.038596,-0.177569,-0.389961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019Q2,0.078855,0.212058,0.917533,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019Q3,0.050255,-0.090462,-0.140794,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020Q1,-0.036575,0.052795,0.269578,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020Q2,0.048010,0.075440,0.202509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020Q3,0.021755,-0.000578,-0.024076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021Q1,0.001332,0.005451,-0.190893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021Q2,0.059403,0.060232,0.050982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021Q3,0.048843,0.083526,0.060078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
df[df['1.01.02.01']==np.inf]

CD_CONTA                                1      1.01     1.01.01     1.01.02  \
CNPJ_CIA           DT_FIM_EXERC
00.001.180/0001-26 2019Q1        0.011112 -0.042091    0.208329    0.136657
00.336.701/0001-04 2016Q1        0.102020 -0.103872  106.586022   -0.992119
01.083.200/0001-18 2020Q3        0.070526  0.011013    0.298308   -0.307692
01.107.327/0001-20 2019Q1        0.107311  0.111331   -0.230103    0.632475
01.938.783/0001-11 2021Q2        0.055274  0.102676   -0.982053         inf
...                                   ...       ...         ...         ...
92.012.467/0001-70 2018Q2        0.005952 -0.000744   -0.087399   -0.130306
                   2019Q2        0.004121  0.009376    0.085923   -0.310173
92.665.611/0001-77 2020Q3        0.415201  0.674743    5.439478         inf
92.754.738/0001-62 2017Q3       -0.016667 -0.046385   -0.205484         inf
92.781.335/0001-02 2021Q1        0.382380  0.359484    1.321748  313.937500

CD_CONTA                         1.01.02.01  1.01.02.01.01  1.01.02.01.02  \
CNPJ_CIA           DT_FIM_EXERC
00.001.180/0001-26 2019Q1               inf            NaN            NaN
00.336.701/0001-04 2016Q1               inf            NaN            inf
01.083.200/0001-18 2020Q3               inf            NaN            inf
01.107.327/0001-20 2019Q1               inf            NaN            NaN
01.938.783/0001-11 2021Q2               inf            NaN            NaN
...                                     ...            ...            ...
92.012.467/0001-70 2018Q2               inf            NaN            NaN
                   2019Q2               inf            inf            NaN
92.665.611/0001-77 2020Q3               inf            NaN            NaN
92.754.738/0001-62 2017Q3               inf            inf            inf
92.781.335/0001-02 2021Q1               inf            NaN            NaN

CD_CONTA                         1.01.02.02  1.01.02.02.01  1.01.02.03  ...  \
CNPJ_CIA           DT_FIM_EXERC                                         ...
00.001.180/0001-26 2019Q1              -1.0            0.0         NaN  ...
00.336.701/0001-04 2016Q1               NaN            NaN         NaN  ...
01.083.200/0001-18 2020Q3               NaN            NaN        -1.0  ...
01.107.327/0001-20 2019Q1               NaN           -1.0         0.0  ...
01.938.783/0001-11 2021Q2               inf            NaN         NaN  ...
...                                     ...            ...         ...  ...
92.012.467/0001-70 2018Q2              -1.0            0.0         NaN  ...
                   2019Q2               NaN            0.0        -1.0  ...
92.665.611/0001-77 2020Q3               NaN            NaN         NaN  ...
92.754.738/0001-62 2017Q3               NaN            NaN         NaN  ...
92.781.335/0001-02 2021Q1               NaN            NaN         NaN  ...

CD_CONTA                         7.11.03  7.11.03.01  7.11.03.02  7.11.03.03  \
CNPJ_CIA           DT_FIM_EXERC
00.001.180/0001-26 2019Q1            NaN         NaN         NaN         NaN
00.336.701/0001-04 2016Q1            NaN         NaN         NaN         NaN
01.083.200/0001-18 2020Q3            NaN         NaN         NaN         NaN
01.107.327/0001-20 2019Q1            NaN         NaN         NaN         NaN
01.938.783/0001-11 2021Q2            NaN         NaN         NaN         NaN
...                                  ...         ...         ...         ...
92.012.467/0001-70 2018Q2            NaN         NaN         NaN         NaN
                   2019Q2            NaN         NaN         NaN         NaN
92.665.611/0001-77 2020Q3            NaN         NaN         NaN         NaN
92.754.738/0001-62 2017Q3            NaN         NaN         NaN         NaN
92.781.335/0001-02 2021Q1            NaN         NaN         NaN         NaN

CD_CONTA                         7.11.04  7.11.04.01  7.11.04.02  7.11.04.03  \
CNPJ_CIA           DT_FIM_EXERC
00.001.180/0001-26 2019Q1            NaN         NaN         NaN         NaN
00.336.701/0001-04 2016Q1            NaN         NaN         NaN         NaN
01.083.200/0001-18 2020Q3            NaN         NaN         NaN         NaN
01.107.327/0001-20 2019Q1            NaN         NaN         NaN         NaN
01.938.783/0001-11 2021Q2            NaN         NaN         NaN         NaN
...                                  ...         ...         ...         ...
92.012.467/0001-70 2018Q2            NaN         NaN         NaN         NaN
                   2019Q2            NaN         NaN         NaN         NaN
92.665.611/0001-77 2020Q3            NaN         NaN         NaN         NaN
92.754.738/0001-62 2017Q3            NaN         NaN         NaN         NaN
92.781.335/0001-02 2021Q1            NaN         NaN         NaN         NaN

CD_CONTA                         7.11.04.04  7.11.05
CNPJ_CIA           DT_FIM_EXERC
00.001.180/0001-26 2019Q1               NaN      NaN
00.336.701/0001-04 2016Q1               NaN      NaN
01.083.200/0001-18 2020Q3               NaN      NaN
01.107.327/0001-20 2019Q1               NaN      NaN
01.938.783/0001-11 2021Q2               NaN      NaN
...                                     ...      ...
92.012.467/0001-70 2018Q2               NaN      NaN
                   2019Q2               NaN      NaN
92.665.611/0001-77 2020Q3               NaN      NaN
92.754.738/0001-62 2017Q3               NaN      NaN
92.781.335/0001-02 2021Q1               NaN      NaN

[186 rows x 497 columns]

In [25]:
df.xs(('2016Q3'), level=1)

CD_CONTA,1,1.01,1.01.01,1.01.02,1.01.02.01,1.01.02.01.01,1.01.02.01.02,1.01.02.02,1.01.02.02.01,1.01.02.03,...,7.11.03,7.11.03.01,7.11.03.02,7.11.03.03,7.11.04,7.11.04.01,7.11.04.02,7.11.04.03,7.11.04.04,7.11.05
CNPJ_CIA,,,,,,,,,,,,,,,,,,,,,
00.001.180/0001-26,0.011992,-0.021155,-0.028056,-0.075112,NaN,NaN,NaN,-0.075112,-0.075112,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00.070.698/0001-11,-0.011181,0.089319,-0.227297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00.336.701/0001-04,0.003209,-0.259962,-0.541827,0.069926,0.069926,NaN,0.069926,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00.622.416/0001-41,-0.021327,0.078616,-0.797373,0.267251,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
00.743.065/0001-27,0.018428,0.026852,0.025927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92.715.812/0001-31,0.016028,-0.008047,0.254509,0.060985,0.060985,NaN,0.060985,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92.754.738/0001-62,-0.023791,-0.044271,-0.085294,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92.781.335/0001-02,-0.026680,-0.046077,0.035891,0.938009,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92.791.243/0001-03,0.088711,0.408659,1.749531,4.029078,NaN,NaN,NaN,4.029078,4.029078,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97.837.181/0001-47,-0.013579,-0.045100,-0.086860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
df.loc(axis=0)[a[a>12].index,:]

13

In [15]:
a = df.groupby('CNPJ_CIA').size()
a[a>12].index

Index(['00.001.180/0001-26', '00.070.698/0001-11', '00.622.416/0001-41',
       '00.743.065/0001-27', '00.776.574/0001-56', '00.864.214/0001-06',
       '01.545.826/0001-07', '01.838.723/0001-27', '01.917.818/0001-36',
       '01.938.783/0001-11',
       ...
       '92.012.467/0001-70', '92.660.570/0001-26', '92.665.611/0001-77',
       '92.690.783/0001-09', '92.693.019/0001-89', '92.715.812/0001-31',
       '92.754.738/0001-62', '92.781.335/0001-02', '92.791.243/0001-03',
       '97.837.181/0001-47'],
      dtype='object', name='CNPJ_CIA', length=264)

In [246]:
acoes[acoes['CNPJ']=='00.001.180/0001-26']

          Código(s)                CNPJ
49  ELET3ELET5ELET6  00.001.180/0001-26

In [259]:
acoes.to_csv('CNPJ-Ticker.csv')

In [257]:
pd.merge(df, acoes, left_on='CNPJ_CIA', right_on='CNPJ')['Código(s)']#.query('`Código(s)`!=1')

0       ELET3ELET5ELET6
1       ELET3ELET5ELET6
2       ELET3ELET5ELET6
3       ELET3ELET5ELET6
4       ELET3ELET5ELET6
             ...
4169              DXCO3
4170              DXCO3
4171              DXCO3
4172              DXCO3
4173              DXCO3
Name: Código(s), Length: 4174, dtype: object

In [261]:
df.head()

CD_CONTA                                1      1.01   1.01.01   1.01.02  \
CNPJ_CIA           DT_FIM_EXERC
00.001.180/0001-26 2012Q2        0.120354  0.014574 -0.281153  0.287845
                   2012Q3        0.017959 -0.010006  0.016352 -0.058716
                   2013Q1       -0.172213  0.155212 -0.206869  0.260170
                   2013Q2       -0.004478 -0.075815 -0.346614 -0.170969
                   2013Q3       -0.001671  0.009712 -0.075484 -0.060596

CD_CONTA                         1.01.02.01  1.01.02.01.01  1.01.02.01.02  \
CNPJ_CIA           DT_FIM_EXERC
00.001.180/0001-26 2012Q2               NaN            NaN            NaN
                   2012Q3               NaN            NaN            NaN
                   2013Q1               NaN            NaN            NaN
                   2013Q2               NaN            NaN            NaN
                   2013Q3               NaN            NaN            NaN

CD_CONTA                         1.01.02.02  1.01.02.02.01  1.01.02.03  ...  \
CNPJ_CIA           DT_FIM_EXERC                                         ...
00.001.180/0001-26 2012Q2          0.287845       0.287845         NaN  ...
                   2012Q3         -0.058716      -0.058716         NaN  ...
                   2013Q1          0.260170       0.260170         NaN  ...
                   2013Q2         -0.170969      -0.170969         NaN  ...
                   2013Q3         -0.060596      -0.060596         NaN  ...

CD_CONTA                         7.11.03  7.11.03.01  7.11.03.02  7.11.03.03  \
CNPJ_CIA           DT_FIM_EXERC
00.001.180/0001-26 2012Q2            NaN         NaN         NaN         NaN
                   2012Q3            NaN         NaN         NaN         NaN
                   2013Q1            NaN         NaN         NaN         NaN
                   2013Q2            NaN         NaN         NaN         NaN
                   2013Q3            NaN         NaN         NaN         NaN

CD_CONTA                         7.11.04  7.11.04.01  7.11.04.02  7.11.04.03  \
CNPJ_CIA           DT_FIM_EXERC
00.001.180/0001-26 2012Q2            NaN         NaN         NaN         NaN
                   2012Q3            NaN         NaN         NaN         NaN
                   2013Q1            NaN         NaN         NaN         NaN
                   2013Q2            NaN         NaN         NaN         NaN
                   2013Q3            NaN         NaN         NaN         NaN

CD_CONTA                         7.11.04.04  7.11.05
CNPJ_CIA           DT_FIM_EXERC
00.001.180/0001-26 2012Q2               NaN      NaN
                   2012Q3               NaN      NaN
                   2013Q1               NaN      NaN
                   2013Q2               NaN      NaN
                   2013Q3               NaN      NaN

[5 rows x 499 columns]

In [191]:
# 'acoes' lê a página que possui os CNPJ's e os Tickers das empresas.
acoes = pd.read_html('https://www.idinheiro.com.br/cnpj-empresas-listadas-b3/')[0].iloc[:, [1,2]]

In [204]:
# É possível resgatar preços de ações desde 2011
import pandas_datareader as web
web.DataReader(f'PETR3.SA', 'yahoo', start='01/01/2011')

                 High        Low       Open      Close      Volume  Adj Close
Date
2011-01-03  30.870001  30.120001  30.719999  30.299999   5064700.0  17.491817
2011-01-04  30.400000  29.540001  30.299999  30.059999  10066400.0  17.353264
2011-01-05  30.670000  29.709999  29.799999  30.629999   5502100.0  17.682322
2011-01-06  30.850000  30.309999  30.549999  30.450001   6889400.0  17.578415
2011-01-07  30.510000  29.910000  30.389999  30.000000   5344500.0  17.318630
...               ...        ...        ...        ...         ...        ...
2022-06-06  34.110001  33.380001  33.889999  33.740002   9285200.0  33.740002
2022-06-07  34.630001  33.549999  33.549999  33.860001  10982800.0  33.860001
2022-06-08  34.230000  33.560001  33.740002  33.730000   7258500.0  33.730000
2022-06-09  33.880001  33.220001  33.740002  33.330002  11378500.0  33.330002
2022-06-10  33.160000  32.360001  33.110001  32.439999   5599500.0  32.439999

[2839 rows x 6 columns]

In [171]:
dataset_ = dataset()

In [179]:
dataset_

CD_CONTA                                   1        1.01     1.01.01  \
CNPJ_CIA           DT_FIM_EXERC
00.001.180/0001-26 2011Q1        149751700.0  34736318.0  12358365.0
                   2012Q2        167774958.0  35242565.0   8883775.0
                   2012Q3        170788053.0  34889942.0   9029039.0
                   2013Q1        141376150.0  40305296.0   7161214.0
                   2013Q2        140743041.0  37249542.0   4679040.0
...                                      ...         ...         ...
97.837.181/0001-47 2020Q2         10969846.0   3960344.0   1598224.0
                   2020Q3         11208491.0   3958054.0   1559745.0
                   2021Q1         11223423.0   3979630.0   1262001.0
                   2021Q2         11890124.0   4219333.0   1326340.0
                   2021Q3         12470872.0   4571755.0   1406024.0

CD_CONTA                           1.01.02  1.01.02.01  1.01.02.01.01  \
CNPJ_CIA           DT_FIM_EXERC
00.001.180/0001-26 2011Q1        6034418.0         0.0            0.0
                   2012Q2        7771395.0         0.0            0.0
                   2012Q3        7315090.0         0.0            0.0
                   2013Q1        9218258.0         0.0            0.0
                   2013Q2        7642226.0         0.0            0.0
...                                    ...         ...            ...
97.837.181/0001-47 2020Q2              0.0         0.0            0.0
                   2020Q3              0.0         0.0            0.0
                   2021Q1              0.0         0.0            0.0
                   2021Q2              0.0         0.0            0.0
                   2021Q3              0.0         0.0            0.0

CD_CONTA                         1.01.02.01.02  1.01.02.02  1.01.02.02.01  \
CNPJ_CIA           DT_FIM_EXERC
00.001.180/0001-26 2011Q1                  0.0   6034418.0      6034418.0
                   2012Q2                  0.0   7771395.0      7771395.0
                   2012Q3                  0.0   7315090.0      7315090.0
                   2013Q1                  0.0   9218258.0      9218258.0
                   2013Q2                  0.0   7642226.0      7642226.0
...                                        ...         ...            ...
97.837.181/0001-47 2020Q2                  0.0         0.0            NaN
                   2020Q3                  0.0         0.0            NaN
                   2021Q1                  0.0         0.0            NaN
                   2021Q2                  0.0         0.0            NaN
                   2021Q3                  0.0         0.0            NaN

CD_CONTA                         1.01.02.03  ...  7.11.03  7.11.03.01  \
CNPJ_CIA           DT_FIM_EXERC              ...
00.001.180/0001-26 2011Q1               NaN  ...      NaN         NaN
                   2012Q2               NaN  ...      NaN         NaN
                   2012Q3               NaN  ...      NaN         NaN
                   2013Q1               NaN  ...      NaN         NaN
                   2013Q2               NaN  ...      NaN         NaN
...                                     ...  ...      ...         ...
97.837.181/0001-47 2020Q2               0.0  ...      NaN         NaN
                   2020Q3               0.0  ...      NaN         NaN
                   2021Q1               0.0  ...      NaN         NaN
                   2021Q2               0.0  ...      NaN         NaN
                   2021Q3               0.0  ...      NaN         NaN

CD_CONTA                         7.11.03.02  7.11.03.03  7.11.04  7.11.04.01  \
CNPJ_CIA           DT_FIM_EXERC
00.001.180/0001-26 2011Q1               NaN         NaN      NaN         NaN
                   2012Q2               NaN         NaN      NaN         NaN
                   2012Q3               NaN         NaN      NaN         NaN
                   2013Q1               NaN         NaN      NaN         NaN
                   2013Q2               NaN         NaN      NaN         NaN
...                                     ...         ...      ...         ...
97.837.181/0001-47 2020Q2               NaN         NaN      NaN         NaN
                   2020Q3               NaN         NaN      NaN         NaN
                   2021Q1               NaN         NaN      NaN         NaN
                   2021Q2               NaN         NaN      NaN         NaN
                   2021Q3               NaN         NaN      NaN         NaN

CD_CONTA                         7.11.04.02  7.11.04.03  7.11.04.04  7.11.05
CNPJ_CIA           DT_FIM_EXERC
00.001.180/0001-26 2011Q1               NaN         NaN         NaN      NaN
                   2012Q2               NaN         NaN         NaN      NaN
                   2012Q3               NaN         NaN         NaN      NaN
                   2013Q1               NaN         NaN         NaN      NaN
                   2013Q2               NaN         NaN         NaN      NaN
...                                     ...         ...         ...      ...
97.837.181/0001-47 2020Q2               NaN         NaN         NaN      NaN
                   2020Q3               NaN         NaN         NaN      NaN
                   2021Q1               NaN         NaN         NaN      NaN
                   2021Q2               NaN         NaN         NaN      NaN
                   2021Q3               NaN         NaN         NaN      NaN

[9592 rows x 499 columns]

In [190]:
acoes = pd.read_html('https://www.idinheiro.com.br/cnpj-empresas-listadas-b3/')[0].iloc[:, [1,2]]

<h3 style='font-size:30px;font-style:italic'> itr_cia_aberta</h3>

In [35]:
pd.read_csv('Statements/itr_cia_aberta_BPA_ind_2011.csv', encoding='ISO-8859-1', sep=';')['DS_CONTA'].head(3)

0         Ativo Total
1         Ativo Total
2    Ativo Circulante
Name: DS_CONTA, dtype: object

In [28]:
pd.read_csv('Statements/itr_cia_aberta_BPA_ind_2012.csv', encoding='ISO-8859-1', sep=';').head(3)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
0,00.000.000/0001-91,2012-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,PENÚLTIMO,2011-12-31,1,Ativo Total,890352257.0,S
1,00.000.000/0001-91,2012-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2012-03-31,1,Ativo Total,913866693.0,S
2,00.000.000/0001-91,2012-03-31,1,BCO BRASIL S.A.,1023,DF Individual - Balanço Patrimonial Ativo,REAL,MIL,PENÚLTIMO,2011-12-31,1.01,Ativo Circulante,518716710.0,S

<h3 style='font-size:30px;font-style:italic'> BPA</h3>

In [63]:
pd.read_csv('Statements/itr_cia_aberta_BPA_con_2011.csv', encoding='ISO-8859-1', sep=';',parse_dates=['DT_FIM_EXERC']).head(3)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
0,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,PENÚLTIMO,2010-12-31,1,Ativo Total,146901002.0,S
1,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,ÚLTIMO,2011-03-31,1,Ativo Total,149751700.0,S
2,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Balanço Patrimonial Ativo,REAL,MIL,PENÚLTIMO,2010-12-31,1.01,Ativo Circulante,32805947.0,S

<h3 style='font-size:30px;font-style:italic'> BPP</h3>

In [29]:
pd.read_csv('Statements/itr_cia_aberta_BPP_con_2011.csv', encoding='ISO-8859-1', sep=';').head(3)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
0,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Balanço Patrimonial Passivo,REAL,MIL,PENÚLTIMO,2010-12-31,2,Passivo Total,146901002.0,S
1,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Balanço Patrimonial Passivo,REAL,MIL,ÚLTIMO,2011-03-31,2,Passivo Total,149751700.0,S
2,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Balanço Patrimonial Passivo,REAL,MIL,PENÚLTIMO,2010-12-31,2.01,Passivo Circulante,18369509.0,S

<h3 style='font-size:30px;font-style:italic'> DFC_MD</h3>

In [31]:
pd.read_csv('Statements/itr_cia_aberta_DFC_MD_con_2011.csv', encoding='ISO-8859-1', sep=';').head(3)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
0,00.070.698/0001-11,2011-03-31,1,CIA ENERGETICA DE BRASILIA,14451,DF Consolidado - Demonstração do Fluxo de Caix...,REAL,MIL,PENÚLTIMO,2010-01-01,2010-03-31,6.01,Caixa Líquido Atividades Operacionais,14679.0,S
1,00.070.698/0001-11,2011-03-31,1,CIA ENERGETICA DE BRASILIA,14451,DF Consolidado - Demonstração do Fluxo de Caix...,REAL,MIL,ÚLTIMO,2011-01-01,2011-03-31,6.01,Caixa Líquido Atividades Operacionais,18238.0,S
2,00.070.698/0001-11,2011-03-31,1,CIA ENERGETICA DE BRASILIA,14451,DF Consolidado - Demonstração do Fluxo de Caix...,REAL,MIL,PENÚLTIMO,2010-01-01,2010-03-31,6.01.01,Recebimento de Consumidores,472870.0,N

<h3 style='font-size:30px;font-style:italic'> DFC_MI</h3>

In [39]:
pd.read_csv('Statements/itr_cia_aberta_DFC_MI_con_2011.csv', encoding='ISO-8859-1', sep=';').head(3)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
0,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Demonstração do Fluxo de Caix...,REAL,MIL,PENÚLTIMO,2010-01-01,2010-03-31,6.01,Caixa Líquido Atividades Operacionais,1619666.0,S
1,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Demonstração do Fluxo de Caix...,REAL,MIL,ÚLTIMO,2011-01-01,2011-03-31,6.01,Caixa Líquido Atividades Operacionais,1189117.0,S
2,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Demonstração do Fluxo de Caix...,REAL,MIL,PENÚLTIMO,2010-01-01,2010-03-31,6.01.01,Caixa Gerado nas Operações,2407485.0,S

<h3 style='font-size:30px;font-style:italic'> DMPL</h3>

In [40]:
pd.read_csv('Statements/itr_cia_aberta_DMPL_con_2011.csv', encoding='ISO-8859-1', sep=';').head(3)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,COLUNA_DF,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
0,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Demonstração das Mutações do ...,REAL,MIL,PENÚLTIMO,2010-01-01,2010-03-31,Capital Social Integralizado,5.01,Saldos Iniciais,26156567.0,S
1,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Demonstração das Mutações do ...,REAL,MIL,ÚLTIMO,2011-01-01,2011-03-31,Capital Social Integralizado,5.01,Saldos Iniciais,26156567.0,S
2,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Demonstração das Mutações do ...,REAL,MIL,PENÚLTIMO,2010-01-01,2010-03-31,"Reservas de Capital, Opções Outorgadas e Ações...",5.01,Saldos Iniciais,26048342.0,S

<h3 style='font-size:30px;font-style:italic'> DRA</h3>

In [41]:
pd.read_csv('Statements/itr_cia_aberta_DRA_con_2011.csv', encoding='ISO-8859-1', sep=';').head(3)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
0,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Demonstração de Resultado Abr...,REAL,MIL,PENÚLTIMO,2010-01-01,2010-03-31,4.01,Lucro Líquido Consolidado do Período,0.0,S
1,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Demonstração de Resultado Abr...,REAL,MIL,ÚLTIMO,2011-01-01,2011-03-31,4.01,Lucro Líquido Consolidado do Período,0.0,S
2,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Demonstração de Resultado Abr...,REAL,MIL,PENÚLTIMO,2010-01-01,2010-03-31,4.02,Outros Resultados Abrangentes,0.0,S

<h3 style='font-size:30px;font-style:italic'> DRE</h3>

In [42]:
pd.read_csv('Statements/itr_cia_aberta_DRE_con_2011.csv', encoding='ISO-8859-1', sep=';').head(3)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
0,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2010-01-01,2010-03-31,3.01,Receita de Venda de Bens e/ou Serviços,6159172.0,S
1,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Demonstração do Resultado,REAL,MIL,ÚLTIMO,2011-01-01,2011-03-31,3.01,Receita de Venda de Bens e/ou Serviços,8551982.0,S
2,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Demonstração do Resultado,REAL,MIL,PENÚLTIMO,2010-01-01,2010-03-31,3.02,Custo dos Bens e/ou Serviços Vendidos,-960060.0,S

<h3 style='font-size:30px;font-style:italic'> DVA</h3>

In [79]:
#f = lambda x: x[x['ORDEM_EXERC']=='ÚLTIMO']
pd.read_csv('Statements/itr_cia_aberta_DVA_con_2011.csv', encoding='ISO-8859-1', sep=';')#.apply(f, axis=1)#.head(3)

,CNPJ_CIA,DT_REFER,VERSAO,DENOM_CIA,CD_CVM,GRUPO_DFP,MOEDA,ESCALA_MOEDA,ORDEM_EXERC,DT_INI_EXERC,DT_FIM_EXERC,CD_CONTA,DS_CONTA,VL_CONTA,ST_CONTA_FIXA
0,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Demonstração de Valor Adicionado,REAL,MIL,PENÚLTIMO,2010-01-01,2010-03-31,7.01,Receitas,6354944.0,S
1,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Demonstração de Valor Adicionado,REAL,MIL,ÚLTIMO,2011-01-01,2011-03-31,7.01,Receitas,8753827.0,S
2,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Demonstração de Valor Adicionado,REAL,MIL,PENÚLTIMO,2010-01-01,2010-03-31,7.01.01,"Vendas de Mercadorias, Produtos e Serviços",6156290.0,S
3,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Demonstração de Valor Adicionado,REAL,MIL,ÚLTIMO,2011-01-01,2011-03-31,7.01.01,"Vendas de Mercadorias, Produtos e Serviços",8551982.0,S
4,00.001.180/0001-26,2011-03-31,1,CENTRAIS ELET BRAS S.A. - ELETROBRAS,2437,DF Consolidado - Demonstração de Valor Adicionado,REAL,MIL,PENÚLTIMO,2010-01-01,2010-03-31,7.01.02,Outras Receitas,198654.0,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89505,97.837.181/0001-47,2011-09-30,1,DURATEX S.A.,21091,DF Consolidado - Demonstração de Valor Adicionado,REAL,MIL,ÚLTIMO,2011-01-01,2011-09-30,7.08.04.03,Lucros Retidos / Prejuízo do Período,187980.0,S
89506,97.837.181/0001-47,2011-09-30,1,DURATEX S.A.,21091,DF Consolidado - Demonstração de Valor Adicionado,REAL,MIL,PENÚLTIMO,2010-01-01,2010-09-30,7.08.04.04,Part. Não Controladores nos Lucros Retidos,283.0,S
89507,97.837.181/0001-47,2011-09-30,1,DURATEX S.A.,21091,DF Consolidado - Demonstração de Valor Adicionado,REAL,MIL,ÚLTIMO,2011-01-01,2011-09-30,7.08.04.04,Part. Não Controladores nos Lucros Retidos,525.0,S
89508,97.837.181/0001-47,2011-09-30,1,DURATEX S.A.,21091,DF Consolidado - Demonstração de Valor Adicionado,REAL,MIL,PENÚLTIMO,2010-01-01,2010-09-30,7.08.05,Outros,0.0,S
89509,97.837.181/0001-47,2011-09-30,1,DURATEX S.A.,21091,DF Consolidado - Demonstração de Valor Adicionado,REAL,MIL,ÚLTIMO,2011-01-01,2011-09-30,7.08.05,Outros,0.0,S